[정치영] Add : 리뷰 작성(post) 엔드포인트
wecode-bootcamp-korea/33-1st-ToWe-backend pull request #11
Opened 2022-05-30 08:05 UTC by Brian-with

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 작성 엔드포인트

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰작성 엔드포인트 구현
2. 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 리뷰 기능 복습

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-05-30 08:51 UTC, bigfanoftim requested changes

2022-05-30 08:51 UTC, bigfanoftim commented on products/views.py
> +
`get()`이 필요하다고 생각하셧다면 그에 맞는 예외처리도 필요해보입니다.

2022-05-30 11:50 UTC, Brian-with commented
conflict 해결 완료

2022-05-31 01:07 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-31 01:07 UTC, merged