Feature/models
wecode-bootcamp-korea/33-1st-ToWe-backend pull request #2
Opened 2022-05-24 09:32 UTC by Brian-with

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가 (model 추가)
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 모델링 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. App 생성 : 3개 (users, products, carts)

2. 각 App별 필요 models.py 작성
  - users : User, Like
  - products : Category, TargetAge, Product, ProductOptions, Image, Color, Review
  - carts : Cart
 
3. Model 작성 후, runserver 테스트 완료
<br />

###  멘토 리뷰 반영
 - table 명 수정
 - 'carts' table에 quantity 항목 추가

## :: ERD
<img width="708" alt="image" src="https://user-images.githubusercontent.com/101810494/169999777-1e8f6b06-cdb7-4693-a92a-69fbb94ef559.png">

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- model 작성 후, 순환참조 오류(circular Import error)가 발생했는데, FK의 class명을 문자열 형식으로 수정하여 문제를 해결할 수 있었음.
<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-05-25 01:04 UTC, bigfanoftim commented
PR명 제대로 적어주세요.

2022-05-25 01:10 UTC, bigfanoftim requested changes
지금 코드가 올바르게 동작하지 않을텐데 Push 해주셨네요.
모델링 PR이면 올바르게 테이블이 생성되는지 확인하고 push해야 합니다. 따라서 migrations 파일도 같이 올라와야 합니다.
만약 지금 같은 상황이면 머지된 이후에 회원가입 기능에 migrations 파일이 같이 올라올 겁니다. 혹은 migrations 파일만 따로 올리는 PR이 필요하겠죠.

- 불필요한 주석 전부 다 지워주세요. 프로젝트의 main 브랜치에는 실제 필요한 코드만 있어야 합니다.
- 네이밍 컨벤션 다시 한 번 확인하세요.
- migrations 파일 생성하고 DB에 테이블이 올바르게 생성되었는지 확인해야 합니다.

2022-05-25 01:10 UTC, bigfanoftim commented on carts/models.py
> +# from users.models import User
```suggestion
```

2022-05-25 10:50 UTC, Brian-with commented
- PR명 수정완료
- migration 완료 및 DB 테이블 생성 확인
- 불필요한 주석 삭제
- 네이밍 컨벤션 재확인 및 수정
- 런서버 테스트 완료

수정사항 추가해서 다시 리뷰 요청 드립니다.

2022-05-26 02:39 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-26 02:39 UTC, merged