제품상세 1.0
wecode-bootcamp-korea/33-1st-ToWe-backend pull request #4
Opened 2022-05-26 07:42 UTC by ByeonghwiJeong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가 
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품상세 페이지 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 제품 상세페이지API **GET : {{url}}/product/product_id**

<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170439148-22c8a008-57f0-4372-a4c2-cad124f384e9.png">

2. PK값만 받아서 데이터 전달

- 전달 데이터: product_id, name, price, description, image_url(여러개일수있음), color(여러개일수있음)
![image](https://user-images.githubusercontent.com/95831345/170438681-3cb4420e-1b54-474c-8fb5-a36b77a0a6d1.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- models구조
  - Product 와 Color 테이블 사이에 ProductOption테이블이 각각 Product와 Color를 외래키참조
- QuerySet 이 아닌 Product객체( product = Product.objects.get(pk = product_id) )에서 _set 역참조 사용
<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170441556-cb513476-7583-4bb3-bc70-e18a55ac57c4.png">
  - 결론: product.productoption_set.all()을 for문을 사용후 나오는 객체i에 i.color.color사용  
<br />

## :: 기타 질문 및 특이 사항
- ❌

2022-05-26 07:51 UTC, bigfanoftim commented
- PR 타이틀 올바르게 수정해주세요. `[33기 정병휘] 제품 상세 정보 API`

2022-05-26 07:51 UTC, bigfanoftim requested changes
들여쓰기 4개로 전체 다 수정해주세요.

2022-05-26 08:09 UTC, ByeonghwiJeong commented
들여쓰기 & PR 타이틀 수정완료 했습니다

2022-05-26 09:29 UTC, ByeonghwiJeong commented
수정완료 했습니다

## :: 추가 성장 포인트(알게된점)
- 문제 : Vscode 상에서는 indentation error 발생X but Github에서는 indentation 들여쓰기 크기가 달라짐
- 원인 : Tab으로 들여쓰기시 space 공백 4칸이 아닌 tab자체로 들여쓰기 됨
- 해결방법
  - ```Editor: Insert Space``` 체크 - 탭키를 공백으로 바꿔줌 
  - ```Editor: Detect Indentation``` 체크해제 - insert space적용을 위해서 해당 옵션을 체크 해제해줘야함
  
<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170459554-c63f136a-7b07-4e60-8a29-d329443219c9.png">
 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170460231-295908b2-e0d1-4958-829b-6311d4307d96.png">

2022-05-26 09:39 UTC, bigfanoftim requested changes

2022-05-26 09:39 UTC, bigfanoftim commented on products/views.py
> +            product = Product.objects.get(pk = product_id)
```suggestion
            product = Product.objects.get(id = product_id)
```

2022-05-26 09:39 UTC, bigfanoftim commented on products/views.py
> +                    'color' :colors,
가독성을 위해 `:`를 기준으로 정렬해주세요.

2022-05-26 09:39 UTC, bigfanoftim commented on products/views.py
> +            return JsonResponse({'product_detail': product_detail}, status =200)
```suggestion
            return JsonResponse({'results': product_detail}, status=200)
```

2022-05-26 09:56 UTC, ByeonghwiJeong commented
변경했습니다.
- pk > id
- : 기준 정렬
- JsonResponse에서 'results'

2022-05-27 01:01 UTC, bigfanoftim requested changes

2022-05-27 01:01 UTC, bigfanoftim commented on products/views.py
> +            product_detail = [
리스트일 필요가 없는데 `[]`로 감싼 이유가 있나요?

2022-05-27 02:14 UTC, ByeonghwiJeong commented on products/views.py
> +            product_detail = [
수정완료했습니다

2022-05-27 02:21 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-27 02:21 UTC, merged