[33기 정병휘] 제품 리스트 API
wecode-bootcamp-korea/33-1st-ToWe-backend pull request #7
Opened 2022-05-27 06:49 UTC by ByeonghwiJeong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품리스트 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
### 1. ``{{url}}/products``  기준 제품리스트 구현
- Resource(product) 기준 URI 설계 - ```urls.py```
<img width="600" alt="image" src="https://user-images.githubusercontent.com/95831345/170639030-e59f2164-4f05-4b9d-94f8-28b033c2975d.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/95831345/170639113-b76782db-7ca2-4aee-8a10-1ca35e663027.png">

### 2. GET방식으로 리스트 Json반환
- **filter** : **카테고리**(레고,인형,퍼즐,자동차), **검색어**(속성명__contains = "검색어")
- **order_by** : 최신순('-id'), 높은/낮은 가격순('-price'/'price'), 높은/낮은 연령순('-age'/'age')

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
### 1. ``filter()``  내부에 조건이 들어가지않으면 all()과 같은 결과 출력
### 2. Product ▶️ TargetAge 관계에서 TargetAge의 age의 값을 기준으로 정렬목표
- 처음에는 그냥 taget_age_id를 기준으로 정렬하면 되므로 아래와같이 방법을 선택함
<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170642876-47dea6a9-f9f0-44eb-87aa-c8f255d8fc19.png">
- target_age 테이블에서 id 값과 그 속성인 age값의 크기순서가 일치해서 결과적으로는 문제가 없으나 age와 id 크기 순이 맞지않으면 문제 발생하여 아래와 같이 정렬 기준을 개선함
<img width="750" alt="image" src="https://user-images.githubusercontent.com/95831345/170643111-73584ce5-72ce-4e27-8f09-f224bcba86b7.png">
- target_age_id 에서 ```더블언더바 __``` 를 붙히면 그 참조된 테이블의 속성값에 접근 가능해짐

<br />

## :: 기타 질문 및 특이 사항
- ❌

2022-05-27 08:34 UTC, bigfanoftim requested changes

2022-05-27 08:34 UTC, bigfanoftim commented on products/views.py
> +        }
dict로 관리하는 특별한 이유가 있나요?

2022-05-27 09:34 UTC, ByeonghwiJeong commented on products/views.py
> +        }
정렬 기준을 프론트와 통신할떄 '-id' '-price' 'price' '-target_age_id__age' 'target_age_id__age'
정해준다면 상관없을것같습니다.

아니면 저런 dict으로 주었을때 정렬 기준 key값이 불일치했을떄 try except 으로 예외처리를 해주는것도 좋을것같습니다

방법1)
dict을지우고 프론트간에 key값을 정확히한다.
방법2)
try except 구문으로 sort값이 잘못들어왔을때 대비해서 예외처리를 한다.

2가지 수정방안이 있을것같습니다 어떤식으로 하는것을 추천해주시나요?

2022-05-27 09:37 UTC, ByeonghwiJeong commented on products/views.py
> +        }
우선 생각한 방안중 방법2로 수정하도록 하겠습니다

2022-05-27 10:02 UTC, bigfanoftim commented on products/views.py
> +        }
try except 구문으로 sort 값이 잘못들어왔는지 체크하려면 어차피 Key Error에 걸려 정확한 에러메세지를 리턴해줄수는 없어 보입니다.
만약 예외처리를 위함이라면 아래와 같은 방식으로 진행해주세요!
```python
sort = ...

if not sort_dict.get(sort):
...
```

2022-05-30 03:38 UTC, ByeonghwiJeong commented on products/views.py
> +        }
```if not sort_dict.get(sort): ```
으로 반영완료했습니다

2022-05-30 04:09 UTC, bigfanoftim requested changes

2022-05-30 04:09 UTC, bigfanoftim commented on products/views.py
> +        category = request.GET.get('category')
불필요한 줄바꿈 지워주세요~
```suggestion
class ProductListView(View):
    def get(self, request):
        category = request.GET.get('category')
```

2022-05-30 04:09 UTC, bigfanoftim commented on products/views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
KeyError 메세지로 반환할거면 try except를 쓰는게 낫지 않나요?
해당 예외처리에 대해 명확한 메세지를 전달하고 싶으시다면 if문으로 처리하라는 말이었습니다~

2022-05-30 12:06 UTC, ByeonghwiJeong commented on products/views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
key_error가 아닌 sort_key_error로 명확히 해주고
불필요한 줄바꿈 삭제했습니다.

2022-05-30 13:49 UTC, ByeonghwiJeong commented
좋아요 기준 정렬 베스트 구현위해서 
`products = Product.objects.filter(q).annotate(like_count=Count('likeproduct')).order_by(sort_dict[sort])[offset:offset+limit]`
으로 annotate 추가후 
sortdict에 key:'best' , value:'-like_count' 추가했습니다.

2022-05-31 01:06 UTC, bigfanoftim commented
Conflict만 해결해주세요 병휘님!

2022-05-31 01:32 UTC, ByeonghwiJeong commented
충돌 해결 완료했습니다.

2022-05-31 02:11 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-31 02:11 UTC, merged